#!/bin/bash
if [ "$XD_HOME" == "" ] 
then
  XD_HOME=~/spring-xd/spring-xd-1.0.0.BUILD-SNAPSHOT
fi
 
./gradlew build

echo "installing artifacts in $XD_HOME"

cp modules/processor/*.xml $XD_HOME/xd/modules/processor
cp scripts/*.groovy $XD_HOME/xd/modules/processor/scripts
cp hashtag-analyzer/build/libs/hashtag-analyzer.jar $XD_HOME/xd/lib
cp hashtag-analyzer/build/libs/hashtag-analyzer.jar $XD_HOME/gemfire/lib
cp config/twitter-demo.xml $XD_HOME/gemfire/config
# Dependent jars needed by groovy script and gemfire
cp $XD_HOME/xd/modules/source/twittersearch/lib/spring-social-*.jar $XD_HOME/xd/lib
cp $XD_HOME/xd/modules/source/twittersearch/lib/spring-social-*.jar $XD_HOME/gemfire/lib